version: '3'
services:
  master:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ROLE: "master"
      SENTINELS: "sentinel-1:9090,sentinel-2:9090"
    depends_on:
      - sentinel-1
      - sentinel-2
    networks:
      - replicated_log
  sentinel-1:
    build:
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      ROLE: "sentinel"
      GRPC_PORT: 9090
    networks:
      - replicated_log
  sentinel-2:
    build:
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    environment:
      ROLE: "sentinel"
      GRPC_PORT: 9090
    networks:
      - replicated_log

networks:
  replicated_log:
